import React from "react";
import Button from "../Button/Button";
import "./style.scss";
export default function HomeDescription() {
  return (
    <section className="home-description">
      <h2>
        Trendy Clothing & Accessories at Dress Up - An Online Dress Boutique
      </h2>
      <p>
        DRESS UP IS A WOMEN&apos;S CLOTHING BOUTIQUE CARRYING A VARIETY OF FITS,
        STYLES, AND PATTERNS FOR WOMEN OF ALL AGES, SHAPES, AND SIZES. WE OFFER
        A DIVERSE COLLECTION OF NEW PRODUCTS EVERY SINGLE WEEK, INCLUDING YOUR
        FAVORITE CLOTHING ITEMS: CUTE ROMPERS, MAXI DRESSES, KNIT SWEATERS,
        OVERSIZED TOPS, AND LIGHTWEIGHT CARDIGANS, AS WELL AS TRENDY SHOES,
        ACCESSORIES, JEWELRY, ACTIVEWEAR, LOUNGEWEAR, AND SO MUCH MORE. DRESS
        UP&apos;S TRENDY, YET WEARABLE CLOTHES WILL HAVE YOU FEELING LIKE YOUR
        BEST SELF, NO MATTER WHERE YOU&apos;RE HEADED. YOU CAN SHOP WITH US
        ONLINE OR AT ANY OF OUR RETAIL LOCATIONS ACROSS THE SOUTHEAST, INCLUDING
        STORES IN GEORGIA, ALABAMA, SOUTH CAROLINA, AND TENNESSEE. GET FREE
        SHIPPING ON ALL ORDERS OVER $49, AND FEEL FREE TO REACH OUT TO US AT
        678.989.2006 WITH ANY QUESTIONS. DON&apos;T MISS OUT - COME SEE WHY
        DRESS UP IS ONE OF THE FASTEST GROWING ONLINE DRESS BOUTIQUES IN THE
        UNITED STATES!
      </p>
      <Button>SHOP OUR NEWEST ARRIVALS</Button>
    </section>
  );
}
